/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproject;

import java.awt.Color;
import java.security.SecureRandom;
import javax.swing.JOptionPane;


public class AdditionEasy extends javax.swing.JFrame {

    /**
     * Creates new form Subtraction
     */
    public AdditionEasy() {
        initComponents();
        SecureRandom rand = new SecureRandom();
        Random1 =  rand.nextInt(20);
        Random2 =  rand.nextInt(30);
        numTF1.setText(Random1+"");
        numTF2.setText(Random2+"");
        numTF3.setBackground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numTF1 = new javax.swing.JTextField();
        questionbtn = new javax.swing.JButton();
        ansBtn = new javax.swing.JButton();
        numTF2 = new javax.swing.JTextField();
        numTF3 = new javax.swing.JTextField();
        ansTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ansBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(21, 14, 86));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 255, 191));
        jLabel1.setText("What is");

        numTF1.setEditable(false);
        numTF1.setBackground(new java.awt.Color(21, 14, 86));
        numTF1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        numTF1.setForeground(new java.awt.Color(255, 255, 255));
        numTF1.setBorder(null);

        questionbtn.setBackground(new java.awt.Color(21, 14, 86));
        questionbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        questionbtn.setForeground(new java.awt.Color(40, 255, 191));
        questionbtn.setText("Next Question");
        questionbtn.setBorder(null);
        questionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionbtnActionPerformed(evt);
            }
        });

        ansBtn.setBackground(new java.awt.Color(21, 14, 86));
        ansBtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ansBtn.setForeground(new java.awt.Color(40, 255, 191));
        ansBtn.setText("Answer");
        ansBtn.setBorder(null);
        ansBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansBtnActionPerformed(evt);
            }
        });

        numTF2.setEditable(false);
        numTF2.setBackground(new java.awt.Color(21, 14, 86));
        numTF2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        numTF2.setForeground(new java.awt.Color(255, 255, 255));
        numTF2.setBorder(null);

        numTF3.setEditable(false);
        numTF3.setBackground(new java.awt.Color(21, 14, 86));
        numTF3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        numTF3.setForeground(new java.awt.Color(255, 5, 9));
        numTF3.setBorder(null);

        ansTF.setBackground(new java.awt.Color(21, 14, 86));
        ansTF.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ansTF.setForeground(new java.awt.Color(255, 255, 255));
        ansTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 255, 191), 3, true));
        ansTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansTFActionPerformed(evt);
            }
        });
        ansTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ansTFKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 255, 191));
        jLabel2.setText("Plus");

        ansBtn1.setBackground(new java.awt.Color(21, 14, 86));
        ansBtn1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ansBtn1.setForeground(new java.awt.Color(40, 255, 191));
        ansBtn1.setText("Back");
        ansBtn1.setBorder(null);
        ansBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ansBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(questionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ansBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(numTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(numTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(numTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(ansTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 265, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ansBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(questionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(numTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ansTF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)))))
                .addComponent(ansBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionbtnActionPerformed
         SecureRandom rand = new SecureRandom();
        Random1 =  rand.nextInt(20);
        Random2 =  rand.nextInt(30);
        numTF1.setText(Random1+"");
        numTF2.setText(Random2+"");
        numTF3.setBackground(Color.blue);    
    }//GEN-LAST:event_questionbtnActionPerformed

    private void ansBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansBtnActionPerformed
        String num = ansTF.getText();
                if (num.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a number", "FeedBackMessage", JOptionPane.WARNING_MESSAGE);
            return;
            
        }
          
        if (!num.matches("\\d+")) {
             JOptionPane.showMessageDialog(this,"Please input number", "FeedBackMessage", JOptionPane.WARNING_MESSAGE);
             return;
            
        }
        int  answer = Integer.parseInt(num);
        int  ans = Random1 + Random2;
        if(answer==ans){
            numTF3.setBackground(Color.green);
        }

        else{
            numTF3.setBackground(Color.red);
        }
    }//GEN-LAST:event_ansBtnActionPerformed

    private void ansBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansBtn1ActionPerformed
          QuizOption qO = new QuizOption();
          qO.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_ansBtn1ActionPerformed

    private void ansTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansTFActionPerformed

    private void ansTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ansTFKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ansTFKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdditionEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdditionEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdditionEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdditionEasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdditionEasy().setVisible(true);
            }
        });
    }
    
    
                int Random2;
                 int Random1;
                

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ansBtn;
    private javax.swing.JButton ansBtn1;
    private javax.swing.JTextField ansTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numTF1;
    private javax.swing.JTextField numTF2;
    private javax.swing.JTextField numTF3;
    private javax.swing.JButton questionbtn;
    // End of variables declaration//GEN-END:variables
}
