/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproject;

import java.security.SecureRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author DJ FB
 */
public class MultiplyHard extends javax.swing.JFrame {

    private int Random1;
    private int Random2;

    /**
     * Creates new form MultiplyHard
     */
    public MultiplyHard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        answerTF = new javax.swing.JTextField();
        mulNum2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        quesbtn = new javax.swing.JButton();
        mulNum1 = new javax.swing.JTextField();
        checkBTn = new javax.swing.JTextField();
        answerBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(21, 14, 86));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 255, 191));
        jLabel1.setText("What is");

        answerTF.setBackground(new java.awt.Color(21, 14, 86));
        answerTF.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        answerTF.setForeground(new java.awt.Color(40, 255, 191));
        answerTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 255, 191), 3, true));

        mulNum2.setEditable(false);
        mulNum2.setBackground(new java.awt.Color(21, 14, 86));
        mulNum2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        mulNum2.setForeground(new java.awt.Color(255, 255, 255));
        mulNum2.setBorder(null);
        mulNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulNum2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 255, 191));
        jLabel2.setText("Multiply By");

        quesbtn.setBackground(new java.awt.Color(21, 14, 86));
        quesbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        quesbtn.setForeground(new java.awt.Color(40, 255, 191));
        quesbtn.setText("Next Question");
        quesbtn.setBorder(null);
        quesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quesbtnActionPerformed(evt);
            }
        });

        mulNum1.setEditable(false);
        mulNum1.setBackground(new java.awt.Color(21, 14, 86));
        mulNum1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        mulNum1.setForeground(new java.awt.Color(255, 255, 255));
        mulNum1.setBorder(null);
        mulNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulNum1ActionPerformed(evt);
            }
        });

        checkBTn.setEditable(false);
        checkBTn.setBackground(new java.awt.Color(21, 14, 86));
        checkBTn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkBTn.setForeground(new java.awt.Color(255, 5, 9));
        checkBTn.setBorder(null);
        checkBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBTnActionPerformed(evt);
            }
        });

        answerBtn.setBackground(new java.awt.Color(21, 14, 86));
        answerBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        answerBtn.setForeground(new java.awt.Color(40, 255, 191));
        answerBtn.setText("Answer");
        answerBtn.setBorder(null);
        answerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(21, 14, 86));
        backBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(40, 255, 191));
        backBtn.setText("Back");
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(mulNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(answerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(answerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(checkBTn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(quesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(mulNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(quesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mulNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBTn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(252, 252, 252))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(answerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(answerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(mulNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mulNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mulNum2ActionPerformed

    private void quesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quesbtnActionPerformed
        SecureRandom rand = new SecureRandom();
        Random1 = 2 + rand.nextInt(70);
        Random2 = 2 + rand.nextInt(60);
        mulNum2.setText(Random1+"");
        mulNum1.setText(Random2+"");
        checkBTn.setText(" null ");
    }//GEN-LAST:event_quesbtnActionPerformed

    private void mulNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mulNum1ActionPerformed

    private void checkBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBTnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBTnActionPerformed

    private void answerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBtnActionPerformed
        String num = answerTF.getText();
                if (num.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a number", "FeedBackMessage", JOptionPane.WARNING_MESSAGE);
            return;
            
        }
          
        if (!num.matches("\\d+")) {
             JOptionPane.showMessageDialog(this,"Please input number", "FeedBackMessage", JOptionPane.WARNING_MESSAGE);
             return;
            
        }
        int  answer = Integer.parseInt(num);
        int  ans = Random1 * Random2;
        if(answer==ans){
            checkBTn.setText("Correct");
        }

        else{
            checkBTn.setText("Wrong");
        }
    }//GEN-LAST:event_answerBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        QuizOption qO = new QuizOption();
        qO.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiplyHard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiplyHard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiplyHard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiplyHard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiplyHard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerBtn;
    private javax.swing.JTextField answerTF;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField checkBTn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mulNum1;
    private javax.swing.JTextField mulNum2;
    private javax.swing.JButton quesbtn;
    // End of variables declaration//GEN-END:variables
}
