/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproject;

/**
 *
 * @author DJ FB
 */
public class QuizOption extends javax.swing.JFrame {

    /**
     * Creates new form QuizOption
     */
    public QuizOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addEasyBtn = new javax.swing.JButton();
        easySubBtn = new javax.swing.JButton();
        easyDivBtn = new javax.swing.JButton();
        easyMulBtn = new javax.swing.JButton();
        easyDivBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Option");

        jPanel1.setBackground(new java.awt.Color(23, 0, 85));

        addEasyBtn.setBackground(new java.awt.Color(205, 17, 59));
        addEasyBtn.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        addEasyBtn.setForeground(new java.awt.Color(255, 255, 255));
        addEasyBtn.setText("+");
        addEasyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEasyBtnActionPerformed(evt);
            }
        });

        easySubBtn.setBackground(new java.awt.Color(205, 17, 59));
        easySubBtn.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        easySubBtn.setForeground(new java.awt.Color(255, 255, 255));
        easySubBtn.setText("Subtraction");
        easySubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easySubBtnActionPerformed(evt);
            }
        });

        easyDivBtn.setBackground(new java.awt.Color(205, 17, 59));
        easyDivBtn.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        easyDivBtn.setForeground(new java.awt.Color(255, 255, 255));
        easyDivBtn.setText("Division");
        easyDivBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyDivBtnActionPerformed(evt);
            }
        });

        easyMulBtn.setBackground(new java.awt.Color(205, 17, 59));
        easyMulBtn.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        easyMulBtn.setForeground(new java.awt.Color(255, 255, 255));
        easyMulBtn.setText("Multiplication");
        easyMulBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyMulBtnActionPerformed(evt);
            }
        });

        easyDivBtn1.setBackground(new java.awt.Color(205, 17, 59));
        easyDivBtn1.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        easyDivBtn1.setForeground(new java.awt.Color(255, 255, 255));
        easyDivBtn1.setText("Back");
        easyDivBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyDivBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(addEasyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(easyDivBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(easySubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 332, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(easyMulBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204))
                    .addComponent(easyDivBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(addEasyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(easyDivBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(easySubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(easyMulBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(easyDivBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void easySubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easySubBtnActionPerformed
            SubtractionEasy sE = new SubtractionEasy();
            sE.setVisible(true);
            
            this.setVisible(false);
    }//GEN-LAST:event_easySubBtnActionPerformed

    private void easyDivBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyDivBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyDivBtnActionPerformed

    private void easyMulBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyMulBtnActionPerformed
       MultiplyEasy mE = new MultiplyEasy();
       mE.setVisible(true);
       
       this.setVisible(false);
    }//GEN-LAST:event_easyMulBtnActionPerformed

    private void easyDivBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyDivBtn1ActionPerformed
        MathsQuiz mZ1 = new MathsQuiz();
        mZ1.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_easyDivBtn1ActionPerformed

    private void addEasyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEasyBtnActionPerformed
        AdditionEasy qO = new AdditionEasy();
        qO.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_addEasyBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEasyBtn;
    private javax.swing.JButton easyDivBtn;
    private javax.swing.JButton easyDivBtn1;
    private javax.swing.JButton easyMulBtn;
    private javax.swing.JButton easySubBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
