/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiproject;
import javax.swing.JOptionPane;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.SecureRandom;
import java.sql.SQLException;

import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author DJ FB
 */
public class SeasonalChallenge extends javax.swing.JFrame {
         public int  getScare(){
             return Scores;
         }
    
         int Scores = 0;

    /**
     * Creates new form SeasonalChallenge
     */
    
    Timer timer;
     
       int counter= 20;
    Boolean isIt = false;
    public SeasonalChallenge() {
        initComponents();
        JOptionPane.showMessageDialog(this, "Answer questions and rise to the top in 20 seconds", "FeedBackMessage", JOptionPane.WARNING_MESSAGE);
         SecureRandom rande = new SecureRandom();
        int yh = 1 + rande.nextInt(4);
        Call(yh);
         timer = new Timer(2000, new ActionListener() {
              @Override
              public void actionPerformed(ActionEvent e) {
                  counter--;
                  timeLeft.setText(counter+"");
                  if (counter == 10) {
                      timeLeft.setForeground(Color.red);
                      
                     
                      
                  }
                   if (counter== 0) {
              timer.stop();
              ansTF.setText(" ");
                jLabel1.setText(" ");
                jLabel3.setText(" "); 
                jLabel4.setText(" ");
                jLabel2.setText(" ");
                  numTF1.setText(" ");
             numTF2.setText(" ");
               numTF4.setText(" ");
                 numTF5.setText(" ");
                
                    name =  JOptionPane.showInputDialog("Enter Name");
                JLbScore.setText("Score");
                jLbPoint.setText(Scores+"");
                //jLbName.setText(name);
                //jlbUS.setText("Username");
                
               
            
        }
              }
          });
          timer.start();
         
     
         
    
       
         
  }
    

 
    
   
               
     int ans;
     String name;
     int Random1;
     int Random2;
     int Random3;
       int sAns;   
          
          

     
     
     
    public  void Call(int value){
        if (value == 1) {
        SecureRandom rand = new SecureRandom();
         jLabel1.setText("What is");
        jLabel3.setText(" "); 
        jLabel4.setText(" ");
        jLabel2.setText("Plus");
        Random1 =  rand.nextInt(20);
        Random2 =  rand.nextInt(30);
        numTF1.setText(Random1+"");
        numTF2.setText(Random2+"");
          numTF4.setText(" ");
             ans = Random1 + Random2;
          
  
        }
        
        if (value == 2) {   
        SecureRandom rande = new SecureRandom();
        jLabel1.setText("What is");
        jLabel3.setText(" "); 
        jLabel4.setText(" ");
        jLabel2.setText("Minus");
        Random1 = 10 + rande.nextInt(20);
        Random2 = 1 + rande.nextInt(10);
        numTF1.setText(Random1+"");
        numTF2.setText(Random2+"");
        numTF4.setText(" ");
        sAns = Random1 - Random2;
        
            
        }
        
        if (value == 3) {
             SecureRandom rande = new SecureRandom();
             jLabel2.setText(" ");
             jLabel1.setText("Find the");
             jLabel3.setText("Perimeter of a");
             jLabel4.setText("Square whose side is");
             Random3 =  rande.nextInt(40/2)*2;
             numTF4.setText(Random3+"");
             numTF1.setText(" ");
             numTF2.setText(" ");
             
            
        }
        
        if (value == 4) {
             SecureRandom rande = new SecureRandom();
             jLabel2.setText(" ");
             jLabel1.setText("Find the");
             jLabel3.setText("Perimeter of a");
             jLabel4.setText("Circle whose radius is");
             Random3 =  ( 1 + rande.nextInt(13))*7;
             numTF4.setText(Random3+"");
             numTF1.setText(" ");
             numTF2.setText(" ");
        
            
        }
       
    }
 
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ansTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();
        numTF1 = new javax.swing.JTextField();
        numTF2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numTF4 = new javax.swing.JTextField();
        numTF5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        timeLeft = new javax.swing.JLabel();
        JLbScore = new javax.swing.JLabel();
        jlbUS = new javax.swing.JLabel();
        jLbName = new javax.swing.JLabel();
        jLbPoint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(21, 14, 86));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 255, 191));
        jLabel1.setText("What is");

        ansTF.setBackground(new java.awt.Color(21, 14, 86));
        ansTF.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ansTF.setForeground(new java.awt.Color(255, 255, 255));
        ansTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 255, 191), 3, true));
        ansTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansTFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 255, 191));

        backBtn1.setBackground(new java.awt.Color(21, 14, 86));
        backBtn1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backBtn1.setForeground(new java.awt.Color(40, 255, 191));
        backBtn1.setText("Back");
        backBtn1.setBorder(null);
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        numTF1.setEditable(false);
        numTF1.setBackground(new java.awt.Color(21, 14, 86));
        numTF1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        numTF1.setForeground(new java.awt.Color(255, 255, 255));
        numTF1.setBorder(null);

        numTF2.setEditable(false);
        numTF2.setBackground(new java.awt.Color(21, 14, 86));
        numTF2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        numTF2.setForeground(new java.awt.Color(255, 255, 255));
        numTF2.setBorder(null);
        numTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTF2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 255, 191));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 255, 191));

        numTF4.setEditable(false);
        numTF4.setBackground(new java.awt.Color(21, 14, 86));
        numTF4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        numTF4.setForeground(new java.awt.Color(255, 255, 255));
        numTF4.setBorder(null);

        numTF5.setEditable(false);
        numTF5.setBackground(new java.awt.Color(21, 14, 86));
        numTF5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        numTF5.setForeground(new java.awt.Color(255, 255, 255));
        numTF5.setBorder(null);
        numTF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTF5ActionPerformed(evt);
            }
        });

        timeLeft.setBackground(new java.awt.Color(21, 14, 86));
        timeLeft.setFont(new java.awt.Font("Tekton Pro Ext", 3, 24)); // NOI18N
        timeLeft.setForeground(new java.awt.Color(40, 234, 7));
        timeLeft.setText("00");

        JLbScore.setBackground(new java.awt.Color(21, 14, 86));
        JLbScore.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        JLbScore.setForeground(new java.awt.Color(40, 255, 191));

        jlbUS.setBackground(new java.awt.Color(21, 14, 86));
        jlbUS.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jlbUS.setForeground(new java.awt.Color(40, 255, 191));

        jLbName.setBackground(new java.awt.Color(21, 14, 86));
        jLbName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLbName.setForeground(new java.awt.Color(40, 255, 191));

        jLbPoint.setBackground(new java.awt.Color(21, 14, 86));
        jLbPoint.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLbPoint.setForeground(new java.awt.Color(40, 255, 191));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLbScore, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbUS, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ansTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(numTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(numTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(numTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(timeLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(numTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(numTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLbName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbUS, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JLbScore, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ansTF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTF2ActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        isIt = true;
        ansTF.setText(" ");
        
     
        QuizOption qO = new QuizOption();
        qO.setVisible(true);

        this.setVisible(false);
        try
        {

            Scores score = new Scores();
            score.setName(name);
            score.setScores(Scores);

            ScoreRespository.addScores(score);
            System.out.println("Score added");
        }
        catch (SQLException ex)
        {
            System.err.println(ex);
        }
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void ansTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansTFActionPerformed
        // timer.restart();
        String num = ansTF.getText();
        if (num.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a number", "FeedBackMessage", JOptionPane.WARNING_MESSAGE);
            return;

        }

        if (!num.matches("\\d+")) {
            JOptionPane.showMessageDialog(this,"Please input number", "FeedBackMessage", JOptionPane.WARNING_MESSAGE);
            return;

        }
          
        int  answer = Integer.parseInt(num);
               
        double perimter =  Random3 * 4;
        double circle = (2 * 22 * Random3)/7;
    

        if(answer ==ans){

            Scores+=10;
            numTF5.setText(Scores+"");

        }
        else if(answer ==sAns){

            Scores+=10;
            numTF5.setText(Scores+"");

        }
        else if(answer == perimter){

            Scores+=10;
            numTF5.setText(Scores+"");

        }
        else if(answer == circle){

            Scores+=10;
            numTF5.setText(Scores+"");

        }

        else{

        }

        SecureRandom rande = new SecureRandom();
        int yh = 1 + rande.nextInt(4);
        Call(yh);

    }//GEN-LAST:event_ansTFActionPerformed

    private void numTF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTF5ActionPerformed

    }//GEN-LAST:event_numTF5ActionPerformed
             

  
              
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeasonalChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeasonalChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeasonalChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeasonalChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     
       
        
        
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeasonalChallenge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLbScore;
    private javax.swing.JTextField ansTF;
    private javax.swing.JButton backBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLbName;
    private javax.swing.JLabel jLbPoint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbUS;
    private javax.swing.JTextField numTF1;
    private javax.swing.JTextField numTF2;
    private javax.swing.JTextField numTF4;
    private javax.swing.JTextField numTF5;
    private javax.swing.JLabel timeLeft;
    // End of variables declaration//GEN-END:variables
  

}
